---
# based on https://github.com/gitpod-io/template-docker-compose

# multi-repo
additionalRepositories:
  - url: https://github.com/ScilifelabDataCentre/dds_cli
    checkoutLocation: dds_cli

tasks:
  - name: Build backend and run server  
    init: >
      chmod a+x /workspace/ &&
      docker compose build --pull
    command: docker compose --profile cli up

ports:
  - port: 5000  # backend
    onOpen: open-browser
  - port: 1080  # mailcatcher
    onOpen: open-browser
  - port: 9000  # minio
    onOpen: ignore
  - port: 9001  # minio
    onOpen: ignore
  - port: 3306  # db
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
