---
# based on https://github.com/gitpod-io/template-docker-compose

tasks:
  - init: docker compose build --pull && git clone https://github.com/ScilifelabDataCentre/dds_cli.git ../dds_cli
  - command: chmod a+x /workspace/dds_web && docker compose --profile cli up

ports:
  - port: 5000
    onOpen: open-preview
  - port: 1080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
