version: "3.7"
services:
  db:
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile-database
    restart: on-failure
    volumes:
      - ./couchdb-data:/opt/couchdb/data
    ports:
      - 5984:5984
  web:
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile-portal
    depends_on:
      - db
    ports:
      - 8888:8888
    restart: on-failure
    volumes:
      - type: bind
        source: ./
        target: /Data-Delivery-Portal