version: "3.2"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-database
    restart: on-failure
    volumes:
      - ./couchdb-data:/opt/couchdb/data
    ports:
      - 5990:5984
  web:
    build:
      context: ./
      dockerfile: Dockerfile-portal
    depends_on:
      - db
    ports:
      - 8888:8888
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /delivery_portal
