# Trivy: Scan remote image on GHCR on schedule
# Trivy (pronunciation) is a comprehensive and versatile security scanner.
# Trivy has scanners that look for security issues,
# and targets where it can find those issues.
# https://github.com/aquasecurity/trivy
# ---------------------------------
name: Trivy - ghcr image scan
on:
  workflow_dispatch:
    branches:
      - master
      - dev
  schedule:
    - cron: "0 7,13 * * *"
jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure lowercase name
        run: echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr "[:upper:]" "[:lower:]") >> $GITHUB_ENV

      - name: Run Trivy on latest release image
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/${{ env.REPOSITORY_OWNER }}/dds-backend:latest"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to master branch GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
          category: trivy

      - name: Run Trivy on latest dev image
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: "ghcr.io/${{ env.REPOSITORY_OWNER }}/dds-backend:dev"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to dev branch GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
          category: trivy